### ISSUE TITLE
FeatherWing: sda / scl labelling on top right is wrong

### ISSUE THREAD

**Issue by phdegen-sensoryx** [adafruit/Adafruit-LSM6DSOX-LIS3MDL-PCB#1]
you got the labels of the sda and scl lines wrongly assigned on the FeatherWing board. they should be switched.

**Comment by ladyada** [comment]
its documented here
https://learn.adafruit.com/st-9-dof-combo/lsm6dsox-lis3mdl-pinouts#featherwing-power-pins-3065313-5
